### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by KENPOKASMMA1982** [vijaysattigeri/jiosaavndownloader#14]
hello dude...congratulations for this amazing project!please can you write me the steps to use your amazing project?

**Comment by vijaysattigeri** [comment]
Thanks mate. 

Please follow the below steps to get started. 

1. Download the latest source or release package
2. Go to source code directory(The one with `setup.py` file) and issue `pip3 install .`

All done. Now you can use it as follows

>  jiosaavndownloader -u <URL of song/album/playlist/artist>

Please look at the README.md file for more details.

**Comment by KENPOKASMMA1982** [comment]
MY FRIEND THANKS SO MUCH WHERE ANSWER ME!YOU WLL BE VERY KIND IF YOU USE ANYDESK OR TEAMVIWER FOR HELP ME FOR A FEW MINUTES!!!

**Comment by vijaysattigeri** [comment]
![jiosaavndownloader-2 1 1_cmd](https://user-images.githubusercontent.com/39031284/166145370-d044d25a-bd77-4ce7-8760-670442de4f90.png)

**Comment by vijaysattigeri** [comment]
Hope this helps!
